#include <stdlib.h>
#include <sys/types.h>
#include "tos_errors.h"
#include <errno.h>

int32_t MapErrno()
{
	switch (errno)
	{
	case 0:
		return TOS_E_OK;
	case ESRCH:
		return TOS_ESRCH;
	case ECHILD:
		return TOS_ECHILD;
	case EDEADLK:
		return TOS_EDEADLK;
	case ENOTBLK:
		return TOS_ENOTBLK;
	case EISDIR:
		return TOS_EISDIR;
	case EINVAL:
		return TOS_EINVAL;
	case EILSEQ:
		return TOS_EILSEQ;
	case ENOSYS:
		return TOS_ENOSYS;
	case EPERM:
		return TOS_EPERM;
	case ENFILE:
		return TOS_ENFILE;
	case EFBIG:
		return TOS_EFBIG;
	case ELOOP:
		return TOS_ELOOP;
	case EPIPE:
		return TOS_EPIPE;
	case EMLINK:
		return TOS_EMLINK;
	case ENOTEMPTY:
		return TOS_ENOTEMPTY;
	case EEXIST:
		return TOS_EEXIST;
	case ENAMETOOLONG:
		return TOS_ENAMETOOLONG;
	case ENOTTY:
		return TOS_ENOTTY;
	case ERANGE:
		return TOS_ERANGE;
	case EDOM:
		return TOS_EDOM;
	case EIO:
		return TOS_EIO;
	case ENOSPC:
		return TOS_ENOSPC;
	case EUSERS:
		return TOS_EUSERS;
	case EDQUOT:
		return TOS_EDQUOT;
	case ESTALE:
		return TOS_ESTALE;
	case EREMOTE:
		return TOS_EREMOTE;
	case ENOLCK:
		return TOS_ENOLCK;
	case EBADMSG:
		return TOS_EBADMSG;
	case EIDRM:
		return TOS_EIDRM;
	case EMULTIHOP:
		return TOS_EMULTIHOP;
	case ENODATA:
		return TOS_ENODATA;
	case ENOLINK:
		return TOS_ENOLINK;
	case ENOMSG:
		return TOS_ENOMSG;
	case ENOSR:
		return TOS_ENOSR;
	case ENOSTR:
		return TOS_ENOSTR;
	case EOVERFLOW:
		return TOS_EOVERFLOW;
	case EPROTO:
		return TOS_EPROTO;
	case ETIME:
		return TOS_ETIME;
	case E2BIG:
		return TOS_E2BIG;
#ifdef LINUX
	case ERESTART:
		return TOS_ERESTART;
	case ECHRNG:
		return TOS_ECHRNG;
	case EL2NSYNC:
		return TOS_EL2NSYNC;
	case EL3HLT:
		return TOS_EL3HLT;
	case EL3RST:
		return TOS_EL3RST;
	case ELNRNG:
		return TOS_ELNRNG;
	case EUNATCH:
		return TOS_EUNATCH;
	case ENOCSI:
		return TOS_ENOCSI;
	case EL2HLT:
		return TOS_EL2HLT;
	case EBADE:
		return TOS_EBADE;
	case EXFULL:
		return TOS_EXFULL;
	case ENOANO:
		return TOS_ENOANO;
	case EBADSLT:
		return TOS_EBADSLT;
	case EBFONT:
		return TOS_EBFONT;
	case ENONET:
		return TOS_ENONET;
	case ENOPKG:
		return TOS_ENOPKG;
	case EADV:
		return TOS_EADV;
	case ESRMNT:
		return TOS_ESRMNT;
	case ECOMM:
		return TOS_ECOMM;
	case EDOTDOT:
		return TOS_EDOTDOT;
	case ELIBACC:
		return TOS_ELIBACC;
	case ELIBBAD:
		return TOS_ELIBBAD;
	case ELIBSCN:
		return TOS_ELIBSCN;
	case ELIBMAX:
		return TOS_ELIBMAX;
	case ELIBEXEC:
		return TOS_ELIBEXEC;
	case ESTRPIPE:
		return TOS_ESTRPIPE;
	case EUCLEAN:
		return TOS_EUCLEAN;
	case ENOTNAM:
		return TOS_ENOTNAM;
	case ENAVAIL:
		return TOS_ENAVAIL;
	case EREMOTEIO:
		return TOS_EREMOTEIO;
#endif
	case ENOTSOCK:
		return TOS_ENOTSOCK;
	case EDESTADDRREQ:
		return TOS_EDESTADDRREQ;
	case EMSGSIZE:
		return TOS_EMSGSIZE;
	case EPROTOTYPE:
		return TOS_EPROTOTYPE;
	case ENOPROTOOPT:
		return TOS_ENOPROTOOPT;
	case EPROTONOSUPPORT:
		return TOS_EPROTONOSUPPORT;
	case ESOCKTNOSUPPORT:
		return TOS_ESOCKTNOSUPPORT;
	case EOPNOTSUPP:
		return TOS_EOPNOTSUPP;
	case EPFNOSUPPORT:
		return TOS_EPFNOSUPPORT;
	case EAFNOSUPPORT:
		return TOS_EAFNOSUPPORT;
	case EADDRINUSE:
		return TOS_EADDRINUSE;
	case EADDRNOTAVAIL:
		return TOS_EADDRNOTAVAIL;
	case ENETDOWN:
		return TOS_ENETDOWN;
	case ENETUNREACH:
		return TOS_ENETUNREACH;
	case ENETRESET:
		return TOS_ENETRESET;
	case ECONNABORTED:
		return TOS_ECONNABORTED;
	case ECONNRESET:
		return TOS_ECONNRESET;
	case EISCONN:
		return TOS_EISCONN;
	case ENOTCONN:
		return TOS_ENOTCONN;
	case ESHUTDOWN:
		return TOS_ESHUTDOWN;
	case ETIMEDOUT:
		return TOS_ETIMEDOUT;
	case ECONNREFUSED:
		return TOS_ECONNREFUSED;
	case EHOSTDOWN:
		return TOS_EHOSTDOWN;
	case EHOSTUNREACH:
		return TOS_EHOSTUNREACH;
	case EALREADY:
		return TOS_EALREADY;
	case EINPROGRESS:
		return TOS_EINPROGRESS;
	case EAGAIN:
		return TOS_EAGAIN;
	case ENOBUFS:
		return TOS_ENOBUFS;
	case ETOOMANYREFS:
		return TOS_ETOOMANYREFS;
	default:
		return TOS_ERROR;
	}
}
